import { useState } from 'react';
import { LEVELS, getLevel } from '../shared/level';
import type { GameState } from '../shared/types';
import type { CampaignProgress } from './progress';
import { getMissionLearning, CYBERSECURITY_SOURCES } from '../shared/learning';
export function displayTime(ms:number){const seconds=Math.floor(ms/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
export function MissionSelect({progress,onSelect,onBack,onDefender}:{progress:CampaignProgress;onSelect:(id:number)=>void;onBack:()=>void;onDefender:()=>void}){
  return <section className="campaign-screen" aria-labelledby="missions-title">
    <div className="campaign-screen-heading"><div><span className="eyebrow">OPERATION GHOST PROTOCOL</span><h1 id="missions-title">Five ways to close a breach.</h1><p>Each sector introduces one security decision. Your progress stays on this browser.</p></div><button className="secondary-button" onClick={onBack}>Back to heist</button></div>
    <div className="mission-grid">{LEVELS.map(level=>{const result=progress.results[level.id],unlocked=level.id<=progress.unlocked;return <button className={`mission-card ${result?'finished':''}`} key={level.id} disabled={!unlocked} onClick={()=>onSelect(level.id)} aria-label={`${result?'Replay':unlocked?'Start':'Locked'} ${level.title}`}>
      <div className={`mission-map-icon mission-map-${level.id}`} aria-hidden="true"><i/><i/><i/><i/><i/><b/></div>
      <div className="mission-card-top"><span>SECTOR {String(level.id).padStart(2,'0')}</span><strong>{result?'✓ CLEARED':unlocked?'READY':'LOCKED'}</strong></div>
      <h2>{level.title}</h2><p>{level.concept}</p><div className="mission-card-foot"><span>{level.sentries.length} {level.sentries.length===1?'sentry':'sentries'}</span><span>{result?`Best ${displayTime(result.bestMs)} · ${result.bestChips} chips`:unlocked?'Enter sector →':'Complete the previous sector'}</span></div>
    </button>;})}</div>
    <button className="defender-entry" disabled={!progress.results[5]} onClick={onDefender}><span className="defender-entry-symbol" aria-hidden="true">⌘</span><span><strong>The defender’s desk</strong><small>{progress.defenderComplete?'Access rules verified. Replay the final challenge.':'Complete the five heists. Then protect the data while keeping maintenance working.'}</small></span><b>{progress.results[5]?'Open lab →':'LOCKED'}</b></button>
  </section>;
}
export function Debrief({state,onNext,onReplay,onMissions,onInspect}:{state:GameState;onNext:()=>void;onReplay:()=>void;onMissions:()=>void;onInspect:()=>void}){
  const level=getLevel(state.levelId),learning=getMissionLearning(state.levelId);const [choice,setChoice]=useState<string|null>(null);
  const chosen=learning.choices.find(item=>item.id===choice);
  const vault=state.grants.find(grant=>grant.id==='vault'),transit=state.grants.find(grant=>grant.id==='transit');
  const [questionOpen,setQuestionOpen]=useState(false);
  return <><span className="eyebrow">SECTOR {String(level.id).padStart(2,'0')} SECURED</span><h2 id="overlay-title">A clean getaway.</h2><div className="outcome-stat"><strong>{displayTime(state.elapsedMs)}</strong><span>{state.collectedShards.length} CHIPS RECOVERED</span></div>
    <div className="learning-takeaway"><span>WHAT THIS SHOWS</span><h3>{learning.plainTitle}</h3><div className="debrief-run-proof" aria-label="Confirmed in this run">{state.carrying&&<span>Package recovered</span>}{vault?.revoked&&<span>Vault access disabled</span>}{transit&&!transit.revoked&&transit.expiresAt>state.elapsedMs&&<span>Transit still active</span>}</div><p>{learning.takeaway}</p><p className="real-world-link"><strong>On the job</strong>{learning.realWorld}</p></div>
    <details className="learning-check" onToggle={event=>setQuestionOpen(event.currentTarget.open)}><summary>Check your understanding <small>OPTIONAL</small></summary>{questionOpen&&<><p>{learning.question}</p><div>{learning.choices.map(item=><button key={item.id} className={`answer-option ${choice===item.id?'chosen':''}`} onClick={()=>setChoice(item.id)}>{item.label}</button>)}</div>{chosen&&<p className={chosen.correct?'answer-correct':'answer-retry'} role="status">{chosen.feedback}</p>}</>}</details>
    <button className="primary-button" onClick={onNext}>{level.id<5?'Next mission':'Become the defender'}<span aria-hidden="true">→</span></button><div className="debrief-links"><button className="text-button" onClick={onReplay}>Replay sector</button><button className="text-button" onClick={onMissions}>Mission select</button><button className="text-button" onClick={onInspect}>Inspect decisions</button></div>
  </>;
}
export function Credits({progress,onMissions,onDefender}:{progress:CampaignProgress;onMissions:()=>void;onDefender:()=>void}){
  return <section className="campaign-credits" aria-labelledby="credits-title"><div className="completion-sigil" aria-hidden="true">✓</div><span className="eyebrow">GHOST PROTOCOL / COMPLETE</span><h1 id="credits-title">Access restored.<br/><em>On your terms.</em></h1><p>You followed a compromised credential through five sectors, then changed the rules that made the breach possible.</p><div className="completion-proof"><span>Intruder’s vault request <strong>DENIED</strong></span><span>Legitimate maintenance <strong>ALLOWED</strong></span></div><div className="credits-missions">{LEVELS.map(level=><div key={level.id}><span>{String(level.id).padStart(2,'0')} {level.title}</span><strong>{progress.results[level.id]?displayTime(progress.results[level.id].bestMs):'—'}</strong></div>)}</div><div className="credits-actions"><button className="primary-button" onClick={onMissions}>Replay the campaign <span aria-hidden="true">→</span></button><button className="secondary-button" onClick={onDefender}>Return to the defender’s desk</button></div><details className="credits-notes"><summary>About the game and its security concepts</summary><p>Created by Nicholas with Codex. Original facility geometry, drone characters, interface and the soundtrack “The Quiet Way In.” Built with React, Three.js and an authoritative local Node server.</p><p>This is a fictional authorization training network. Gate decisions, expiry, revocation and policy checks execute in code. It does not connect to real systems or certify security skills.</p><div>{CYBERSECURITY_SOURCES.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>)}</div></details></section>;
}
